:contract: 
  :from: Contract.java.shadow
  :to: ./app/src/main/java/${package_name_to_path}/prototype/${screen_name_downcase}/${screen_name_first_letter_uppercase}Contract.java
:screen: 
  :from: Activity.java.shadow
  :to: ./app/src/main/java/${package_name_to_path}/prototype/${screen_name_downcase}/${screen_name_first_letter_uppercase}Activity.java
:presenter: 
  :from: Presenter.java.shadow
  :to: ./app/src/main/java/${package_name_to_path}/prototype/${screen_name_downcase}/${screen_name_first_letter_uppercase}Presenter.java
:layout: 
  :from: layout_activity.xml.shadow
  :to: ./app/src/main/res/layout/shadow_p_${screen_name_downcase}_activity.xml
:i_view:
  :from: IView.java.shadow
  :to: ./app/src/main/java/${package_name_to_path}/prototype/IView.java
:i_presenter:
  :from: IPresenter.java.shadow
  :to: ./app/src/main/java/${package_name_to_path}/prototype/IPresenter.java
:base_presenter:
  :from: BasePresenter.java.shadow
  :to: ./app/src/main/java/${package_name_to_path}/prototype/Presenter.java
